### ISSUE TITLE
audioPipeFd and videoPipeFd used in close() are never initialized.

### ISSUE THREAD

**Issue by smallfly** [timscaffidi/ofxVideoRecorder#21]
In the close() methods there are calls to setNonblocking():
```
//set pipes to non_blocking so we dont get stuck at the final writes
setNonblocking(audioPipeFd);
setNonblocking(videoPipeFd);
```
But it seems that the variables audioPipeFd and videoPipeFd are never initialized.
Should the calls the setNonblocking() be removed?

**Comment by timscaffidi** [comment]
yes it appears those should be moved instead to be called in a function of the audio/video writer threads instead, since the file descriptors are no longer held by the main thread

**Comment by smallfly** [comment]
I'm not sure I understand what you mean. Could give more details?

**Comment by timscaffidi** [comment]
Since the file descriptors moved to the writer threads, the main thead can't see them, so these calls are not going to do what is intended anymore. However, if the audio/video thread classes could have a public method that calls setNonblocking on their internal file descriptors, these new functions could be invoked in the same place as the current calls.

**Comment by smallfly** [comment]
ok I see. I can look in to that later. But what does that mean for the current version of the addon. Could these 'broken' calls be the source of issues at runtime?

**Comment by timscaffidi** [comment]
They may have caused problems, but I haven't had time to adequately test. Thanks for the fix!
